### ISSUE TITLE
为什么我的lomorage安装后打不开？问0

### ISSUE THREAD

**Issue by yingyumo** [lomorage/LomoAgentWin#1]

**Comment by yingyumo** [comment]
win10系统

**Comment by aisnote** [comment]
屏幕上显示什么?
-Elliot

**Comment by aisnote** [comment]
https://docs.lomorage.com/zh/docs/Installation/lomorage-service/installation-win/

**Comment by aisnote** [comment]
可以加微信：lomoware
试试最新的版本：
https://docs.lomorage.com/zh/docs/Installation/lomorage-service/installation-win/

**Comment by aisnote** [comment]
已经修复：
https://docs.lomorage.com/docs/Installation/lomorage-service/installation-win/
