### ISSUE TITLE
你好我设置了主目录 但是没有反应

### ISSUE THREAD

**Issue by ConandSherry** [lomorage/LomoAgentWin#2]
![image](https://user-images.githubusercontent.com/13324408/129451516-247f4d0a-a662-4141-befa-f55e6961684a.png)

**Comment by aisnote** [comment]
你是下载的最新版本吗？

加微信：lomoware

**Comment by aisnote** [comment]
![image](https://user-images.githubusercontent.com/1201634/129466838-5e65dcd7-9b0c-4670-950e-7584b234c0bc.png)

点击 设置目录，然后点击 启动 ， 试试看

加微信：lomoware

**Comment by aisnote** [comment]
试试最新的版本，刚刚修复了 不能设置主目录的问题：
https://docs.lomorage.com/zh/docs/Installation/lomorage-service/installation-win/

**Comment by ConandSherry** [comment]
感谢 现在可以了
