### ISSUE TITLE
程序会自动添加到win7的启动项

### ISSUE THREAD

**Issue by admin05** [lomorage/LomoAgentWin#3]
即使我没有勾选“随Windows启动lomorage服务程序”，每次启动后，lomoagent.exe依然会添加到开机启动项中。我的电脑是win7 64bit。

**Comment by aisnote** [comment]
你不想自动启动， 是吗？我们查一下

**Comment by admin05** [comment]
是的，我不希望它开机自启动。五月份的版本就有这个问题。八月的版本还是一样的问题。

**Comment by aisnote** [comment]
我们查一下，多谢反馈。
-Elliot

**Comment by aisnote** [comment]
已经修复：
https://docs.lomorage.com/docs/Installation/lomorage-service/installation-win/
