### ISSUE TITLE
ios14.4.2 iphone12 pro max 闪退

### ISSUE THREAD

**Issue by whsybs** [lomorage/LomoAgentWin#9]
备份几十张照片后就会卡死闪退，关闭app后手机屏幕还会间歇性黑屏一下又亮起来，手机重启，app卸载重装后还会这样

**Comment by whsybs** [comment]
换老版本解决问题

**Comment by fuji246** [comment]
Windows换老版本？

**Comment by whsybs** [comment]
我是iphone app闪退，换ios老版本，现在用0.8.33蛮稳定的发自我的手机-------- 原始邮件 --------发件人： Jiantao Fu ***@***.***>日期： 2023年4月26日周三 12:03收件人： lomorage/LomoAgentWin ***@***.***>抄送： whsybs ***@***.***>, State change ***@***.***>主    题： Re: [lomorage/LomoAgentWin] ios14.4.2 iphone12 pro max 闪退 (Issue #9)
Windows换老版本？

**Comment by fuji246** [comment]
还能退回老版本？怎么操作的？

**Comment by whsybs** [comment]
搜索引擎搜索：iOS安装旧版app发自我的手机
